theme: jekyll-theme-slate
title: Build to Sell Formula
tagline: Specific advice on how to build something in order to sell it
description: Specific advice on how to build something in order to sell it. Market research, business plan development, resources identification, prototyping, marketing and sales, customer feedback.

# Google Analytics
ga_tracking_id: G-85CSDFN0Y5
